import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { Pressable, StyleSheet, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { colors } from '../theme/tokens';
export type TabKey = 'home' | 'devices' | 'invitations' | 'profile';
const icons: Record<TabKey, keyof typeof Ionicons.glyphMap> = { home: 'home-outline', devices: 'options-outline', invitations: 'mail-outline', profile: 'person-outline' };
export function FloatingNav({ active, onTab, onAdd }: { active: TabKey; onTab: (tab: TabKey) => void; onAdd: () => void }) { const inset = useSafeAreaInsets(); return <View pointerEvents="box-none" style={[s.wrap, { bottom: Math.max(inset.bottom, 12) }]}><View style={s.bar}>{(['home', 'devices'] as TabKey[]).map(k => <Pressable key={k} onPress={() => onTab(k)} style={s.item} accessibilityLabel={k}><Ionicons name={icons[k]} size={24} color={active === k ? colors.primary : colors.muted} /></Pressable>)}<View style={s.space} />{(['invitations', 'profile'] as TabKey[]).map(k => <Pressable key={k} onPress={() => onTab(k)} style={s.item} accessibilityLabel={k}><Ionicons name={icons[k]} size={24} color={active === k ? colors.primary : colors.muted} /></Pressable>)}</View><Pressable onPress={onAdd} style={s.add} accessibilityLabel="Thêm thiết bị"><LinearGradient colors={[colors.primary, colors.secondary]} style={s.addInner}><Ionicons name="add" size={32} color="#fff" /></LinearGradient></Pressable></View>; }
const s = StyleSheet.create({ wrap: { position: 'absolute', left: 20, right: 20, height: 76, justifyContent: 'flex-end' }, bar: { height: 72, borderRadius: 36, backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', shadowColor: '#8F9DC5', shadowOpacity: .25, shadowRadius: 18, shadowOffset: { width: 0, height: 7 }, elevation: 8 }, item: { flex: 1, height: 72, alignItems: 'center', justifyContent: 'center' }, space: { width: 76 }, add: { position: 'absolute', left: '50%', marginLeft: -36, top: -2, shadowColor: colors.secondary, shadowOpacity: .45, shadowRadius: 13, shadowOffset: { width: 0, height: 6 }, elevation: 10 }, addInner: { height: 72, width: 72, borderRadius: 36, alignItems: 'center', justifyContent: 'center', borderWidth: 4, borderColor: colors.background } });
